# Base configs
baseurl: "https://www.jasmin.lol"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Jasmin Garcia Acosta Art"
subtitle: "Welcome to my art collection, from the very first steps!"
author: "Jasmin Garcia Acosta"
header:
 title: "Art"
 subtitle: "by Jasmin Garcia Acosta"
footer:
 name: "Hey there, my name is Jasmin"
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/j.garcia.ac"
  instagram: "https://www.instagram.com/j.garcia.ac"
  github: "https://www.github.com/j.garcia.ac"
